EBandPlannerROS:

  # TRAJECTORY CONTROL
  differential_drive: false

  # velocity limits
  max_vel_lin: 0.5
  max_vel_th: 1.1
  min_vel_lin: 0.3
  min_vel_th: 0.4
  min_in_place_vel_th: 0.1

  # acceleration limits
  max_translational_acceleration: 1.0
  max_rotational_acceleration: 2.0

  # goal tolerance
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.15

  # # angular velocity PID
  # k_prop: 0.5
  # k_damp: 2.25

  # # eband parameters
  # max_acceleration: 0.5
  # virtual_mass: 1.75

  # # connectivity checking
  # eband_min_relative_bubble_overlap_: 0.7

  # # bubble geometric bounds
  # eband_tiny_bubble_distance: 0.01
  # eband_tiny_bubble_expansion: 0.01

  # # optimization - force calculation
  # eband_internal_force_gain: 1.1
  # # default 2.0
  # eband_external_force_gain: 0.9
  # num_iterations_eband_optimization: 2

  # # recursive approximation of bubble equilibrium position based
  # eband_equilibrium_approx_max_recursion_depth: 3
  # eband_equilibrium_relative_overshoot: 0.8
  # eband_significant_force_lower_bound: 0.15